import { Achievement } from './types'

export const ACHIEVEMENTS_DATA: Omit<Achievement, 'unlocked' | 'unlockedAt'>[] = [
  // Fitness achievements
  {
    id: 'ironclad',
    name: 'Ironclad',
    description: 'Reach Fitness Level 10',
    icon: '🏋️',
    categoryId: 'fitness',
    requirement: { type: 'category_level', value: 10, categoryId: 'fitness' },
    rarity: 'uncommon',
  },
  {
    id: 'iron-giant',
    name: 'Iron Giant',
    description: 'Reach Fitness Level 25',
    icon: '💪',
    categoryId: 'fitness',
    requirement: { type: 'category_level', value: 25, categoryId: 'fitness' },
    rarity: 'rare',
  },
  {
    id: 'titan',
    name: 'Titan',
    description: 'Reach Fitness Level 50',
    icon: '🦾',
    categoryId: 'fitness',
    requirement: { type: 'category_level', value: 50, categoryId: 'fitness' },
    rarity: 'epic',
  },
  
  // Business achievements
  {
    id: 'hustler',
    name: 'Hustler',
    description: 'Reach Business Level 10',
    icon: '📈',
    categoryId: 'business',
    requirement: { type: 'category_level', value: 10, categoryId: 'business' },
    rarity: 'uncommon',
  },
  {
    id: 'mogul',
    name: 'Mogul',
    description: 'Reach Business Level 25',
    icon: '💼',
    categoryId: 'business',
    requirement: { type: 'category_level', value: 25, categoryId: 'business' },
    rarity: 'rare',
  },
  {
    id: 'tycoon',
    name: 'Tycoon',
    description: 'Reach Business Level 50',
    icon: '👑',
    categoryId: 'business',
    requirement: { type: 'category_level', value: 50, categoryId: 'business' },
    rarity: 'epic',
  },
  
  // Relationships achievements
  {
    id: 'social-butterfly',
    name: 'Social Butterfly',
    description: 'Reach Relationships Level 10',
    icon: '🦋',
    categoryId: 'relationships',
    requirement: { type: 'category_level', value: 10, categoryId: 'relationships' },
    rarity: 'uncommon',
  },
  {
    id: 'heart-of-gold',
    name: 'Heart of Gold',
    description: 'Reach Relationships Level 25',
    icon: '💛',
    categoryId: 'relationships',
    requirement: { type: 'category_level', value: 25, categoryId: 'relationships' },
    rarity: 'rare',
  },
  
  // Learning achievements
  {
    id: 'bookworm',
    name: 'Bookworm',
    description: 'Reach Learning Level 10',
    icon: '📖',
    categoryId: 'learning',
    requirement: { type: 'category_level', value: 10, categoryId: 'learning' },
    rarity: 'uncommon',
  },
  {
    id: 'scholar',
    name: 'Scholar',
    description: 'Reach Learning Level 25',
    icon: '🎓',
    categoryId: 'learning',
    requirement: { type: 'category_level', value: 25, categoryId: 'learning' },
    rarity: 'rare',
  },
  {
    id: 'sage',
    name: 'Sage',
    description: 'Reach Learning Level 50',
    icon: '🧙',
    categoryId: 'learning',
    requirement: { type: 'category_level', value: 50, categoryId: 'learning' },
    rarity: 'epic',
  },
  
  // Health achievements
  {
    id: 'zen-master',
    name: 'Zen Master',
    description: 'Reach Health Level 10',
    icon: '🧘',
    categoryId: 'health',
    requirement: { type: 'category_level', value: 10, categoryId: 'health' },
    rarity: 'uncommon',
  },
  {
    id: 'wellness-warrior',
    name: 'Wellness Warrior',
    description: 'Reach Health Level 25',
    icon: '🌿',
    categoryId: 'health',
    requirement: { type: 'category_level', value: 25, categoryId: 'health' },
    rarity: 'rare',
  },
  
  // Personal achievements
  {
    id: 'self-starter',
    name: 'Self-Starter',
    description: 'Reach Personal Level 10',
    icon: '⭐',
    categoryId: 'personal',
    requirement: { type: 'category_level', value: 10, categoryId: 'personal' },
    rarity: 'uncommon',
  },
  {
    id: 'renaissance-soul',
    name: 'Renaissance Soul',
    description: 'Reach Personal Level 25',
    icon: '🎨',
    categoryId: 'personal',
    requirement: { type: 'category_level', value: 25, categoryId: 'personal' },
    rarity: 'rare',
  },
  
  // Streak achievements
  {
    id: 'consistent',
    name: 'Consistent',
    description: 'Maintain a 3-day streak',
    icon: '🔥',
    requirement: { type: 'streak', value: 3 },
    rarity: 'common',
  },
  {
    id: 'week-warrior',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '🔥',
    requirement: { type: 'streak', value: 7 },
    rarity: 'uncommon',
  },
  {
    id: 'fortnight-fighter',
    name: 'Fortnight Fighter',
    description: 'Maintain a 14-day streak',
    icon: '🔥',
    requirement: { type: 'streak', value: 14 },
    rarity: 'rare',
  },
  {
    id: 'month-master',
    name: 'Month Master',
    description: 'Maintain a 30-day streak',
    icon: '🔥',
    requirement: { type: 'streak', value: 30 },
    rarity: 'epic',
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Maintain a 100-day streak',
    icon: '💎',
    requirement: { type: 'streak', value: 100 },
    rarity: 'legendary',
  },
  
  // Task completion achievements
  {
    id: 'first-steps',
    name: 'First Steps',
    description: 'Complete your first task',
    icon: '👣',
    requirement: { type: 'tasks_completed', value: 1 },
    rarity: 'common',
  },
  {
    id: 'getting-started',
    name: 'Getting Started',
    description: 'Complete 10 tasks',
    icon: '🚀',
    requirement: { type: 'tasks_completed', value: 10 },
    rarity: 'common',
  },
  {
    id: 'task-slayer',
    name: 'Task Slayer',
    description: 'Complete 50 tasks',
    icon: '⚔️',
    requirement: { type: 'tasks_completed', value: 50 },
    rarity: 'uncommon',
  },
  {
    id: 'centurion',
    name: 'Centurion',
    description: 'Complete 100 tasks',
    icon: '🏛️',
    requirement: { type: 'tasks_completed', value: 100 },
    rarity: 'rare',
  },
  {
    id: 'legendary-grinder',
    name: 'Legendary Grinder',
    description: 'Complete 500 tasks',
    icon: '🏆',
    requirement: { type: 'tasks_completed', value: 500 },
    rarity: 'epic',
  },
  {
    id: 'task-god',
    name: 'Task God',
    description: 'Complete 1000 tasks',
    icon: '⚡',
    requirement: { type: 'tasks_completed', value: 1000 },
    rarity: 'legendary',
  },
  
  // Character level achievements
  {
    id: 'level-5',
    name: 'Rising Star',
    description: 'Reach Character Level 5',
    icon: '⭐',
    requirement: { type: 'level', value: 5 },
    rarity: 'common',
  },
  {
    id: 'level-10',
    name: 'Determined',
    description: 'Reach Character Level 10',
    icon: '🌟',
    requirement: { type: 'level', value: 10 },
    rarity: 'uncommon',
  },
  {
    id: 'level-25',
    name: 'Formidable',
    description: 'Reach Character Level 25',
    icon: '💫',
    requirement: { type: 'level', value: 25 },
    rarity: 'rare',
  },
  {
    id: 'level-50',
    name: 'Legendary',
    description: 'Reach Character Level 50',
    icon: '👑',
    requirement: { type: 'level', value: 50 },
    rarity: 'epic',
  },
  {
    id: 'level-100',
    name: 'Ascended',
    description: 'Reach Character Level 100',
    icon: '🌌',
    requirement: { type: 'level', value: 100 },
    rarity: 'legendary',
  },
  
  // XP achievements
  {
    id: 'xp-1k',
    name: 'Thousand Strong',
    description: 'Earn 1,000 total XP',
    icon: '💰',
    requirement: { type: 'total_xp', value: 1000 },
    rarity: 'common',
  },
  {
    id: 'xp-10k',
    name: 'XP Hunter',
    description: 'Earn 10,000 total XP',
    icon: '💎',
    requirement: { type: 'total_xp', value: 10000 },
    rarity: 'uncommon',
  },
  {
    id: 'xp-50k',
    name: 'XP Hoarder',
    description: 'Earn 50,000 total XP',
    icon: '🏴‍☠️',
    requirement: { type: 'total_xp', value: 50000 },
    rarity: 'rare',
  },
  {
    id: 'xp-100k',
    name: 'XP Overlord',
    description: 'Earn 100,000 total XP',
    icon: '🐉',
    requirement: { type: 'total_xp', value: 100000 },
    rarity: 'epic',
  },
]

export const RARITY_COLORS: Record<string, { bg: string; border: string; text: string }> = {
  common: { bg: 'rgba(148, 163, 184, 0.1)', border: '#94a3b8', text: '#94a3b8' },
  uncommon: { bg: 'rgba(0, 255, 136, 0.1)', border: '#00ff88', text: '#00ff88' },
  rare: { bg: 'rgba(0, 212, 255, 0.1)', border: '#00d4ff', text: '#00d4ff' },
  epic: { bg: 'rgba(168, 85, 247, 0.1)', border: '#a855f7', text: '#a855f7' },
  legendary: { bg: 'rgba(255, 215, 0, 0.1)', border: '#ffd700', text: '#ffd700' },
}

